[tox]
envlist = py{310,311,312,313,314}-tests, qc, docs
isolated_build = true

[testenv:py{310,311,312,313,314}-tests]
package = wheel
wheel_build_env = .pkg
extras = xarray
deps =
    dask[array]
    pytest
    pytest-cov
    scipy
    xarray>=0.15
commands = pytest -v --cache-clear {posargs}

[testenv:docs]
deps = -r{toxinidir}/ci/requirements-docs.txt
commands = sphinx-build -W -b html docs build/sphinx/html

[testenv:qc]
usedevelop = true
deps =
    dask[array]
    flake8
    pytest
    pytest-cov
    scipy
    xarray>=0.15
commands = pytest -v --cov=cfgrib --cov=cf2cdm --cov-report=html --cache-clear {posargs}

[testenv]
passenv = *
